//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catalog.Contracts.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrderEventTypeTitles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderEventTypeTitles() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Catalog.Contracts.Resources.OrderEventTypeTitles", typeof(OrderEventTypeTitles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Завершен процесс согласования!.
        /// </summary>
        public static string ApprovalCompleted {
            get {
                return ResourceManager.GetString("ApprovalCompleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ отменен!.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ изменен!.
        /// </summary>
        public static string Changed {
            get {
                return ResourceManager.GetString("Changed", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Завершен!.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Запущен процесс согласования!.
        /// </summary>
        public static string CreateApprovalWorkflow {
            get {
                return ResourceManager.GetString("CreateApprovalWorkflow", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ создан!.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменен нестандартный модуль!.
        /// </summary>
        public static string CustomModuleModified {
            get {
                return ResourceManager.GetString("CustomModuleModified", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ удален!.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ не принят в производство!.
        /// </summary>
        public static string ExternallyReject {
            get {
                return ResourceManager.GetString("ExternallyReject", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ передан в производство!.
        /// </summary>
        public static string InProduction {
            get {
                return ResourceManager.GetString("InProduction", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавлен комментарий!.
        /// </summary>
        public static string MessageAdded {
            get {
                return ResourceManager.GetString("MessageAdded", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавлены новые фасады..
        /// </summary>
        public static string OrderItemAdded {
            get {
                return ResourceManager.GetString("OrderItemAdded", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменено количество фасадов..
        /// </summary>
        public static string OrderItemQuantityChanged {
            get {
                return ResourceManager.GetString("OrderItemQuantityChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Удален элемент заказа..
        /// </summary>
        public static string OrderItemRemoved {
            get {
                return ResourceManager.GetString("OrderItemRemoved", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Завершено производство..
        /// </summary>
        public static string Produced {
            get {
                return ResourceManager.GetString("Produced", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Не пройден процесс согласования!.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
    }
}
